- name: Ensure pre-receive directory
  ansible.builtin.file:
    path: "/var/opt/gitlab/gitaly/custom_hooks/pre-receive.d"
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Install custom pre-receive hooks
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/var/opt/gitlab/gitaly/custom_hooks/pre-receive.d/{{ item }}"
    mode: "0755"
    owner: root
    group: root
  loop:
    - priv-key-scanner.sh
    - vault-scanner.sh
