# SPDX-FileCopyrightText: 2020 Helmholtz Centre for Environmental Research (UFZ)
# SPDX-FileCopyrightText: 2020 Helmholtz-Zentrum Dresden-Rossendorf (HZDR)
#
# SPDX-License-Identifier: Apache-2.0

---
- name: Add GitLab repo using key from URL.
  when: ansible_facts.os_family == 'Debian'
  ansible.builtin.deb822_repository:
    name: gitlab
    types:
      - deb
    uris: "{{ gitlab_repo_url }}"
    suites:
      - "{{ ansible_facts.distribution_release }}"
    components:
      - main
    signed_by: "{{ gitlab_gpg_key_url }}"
    state: present
    enabled: true

- name: Update APT package cache
  when: ansible_facts.os_family == 'Debian'
  ansible.builtin.apt:
    update_cache: true
  register: gitlab_apt_cache
  check_mode: false
  changed_when:
    - false
    - not ansible_check_mode

- name: Install GitLab Dependencies
  become: true
  ansible.builtin.package:
    name: "{{ gitlab_dependencies }}"
    state: present

- name: Check if VERSION file exists
  ansible.builtin.stat:
    path: "/var/opt/gitlab/gitlab-rails/VERSION"
  register: gitlab_version_file

- name: Wait for background migrations on primary node
  when:
    - gitlab_is_primary
    - gitlab_version_file.stat.exists
    - gitlab_rails_binary.stat.exists
    - gitlab_rails_binary.stat.executable
  block:
    - name: Get the currently installed GitLab version
      ansible.builtin.slurp:
        path: "/var/opt/gitlab/gitlab-rails/VERSION"
      register: gitlab_version_base64

    - name: Set fact about installed GitLab version
      ansible.builtin.set_fact:
        gitlab_installed_version: "{{ gitlab_version_base64['content'] | b64decode | split('-') | first }}"
      check_mode: false

    - name: Wait until all previous background migrations are processed.
      become: true
      ansible.builtin.command:
        # https://forum.gitlab.com/t/gitlab-18-4-0-removes-gitlab-backgroundmigration-remaining/131336
        cmd: gitlab-rails runner -e production 'puts Gitlab::Database::BackgroundMigration::BatchedMigration.select{ |m| not m.finished? and not m.finalized? }'
      register: gitlab_remaining
      until: gitlab_remaining.stdout == ""
      retries: 10
      delay: 10
      check_mode: false
      changed_when: false
      when: gitlab_version == '' or gitlab_installed_version is version(gitlab_version, operator='lt', strict=True)

- name: "Install GitLab and add helper to detect failed reconfigures"
  when: ansible_facts.os_family == 'Debian'
  block:
    - name: Gather package facts
      ansible.builtin.package_facts:
        manager: auto

    - name: Unhold GitLab if it does not contain version info
      ansible.builtin.dpkg_selections:
        name: "{{ gitlab_package_name }}"
        selection: install
      when:
        - "'=' not in gitlab_package_name"
        - gitlab_package_name in ansible_facts.packages

    - name: Install, downgrade or upgrade GitLab.
      become: true
      ansible.builtin.apt:
        name: "{{ gitlab_package_name }}"
        state: "{{ 'present' if gitlab_version | length > 0 else 'latest' }}"
        allow_downgrade: false
        allow_change_held_packages: true
      register: gitlab_install_output
      notify: GitLab has been installed or upgraded
      when: not gitlab_is_initial_dryrun

    - name: Hold GitLab version if version is specified
      ansible.builtin.dpkg_selections:
        name: "{{ gitlab_package_name.split('=')[0] }}"
        selection: hold
      when: "'=' in gitlab_package_name"

  rescue:

    - name: Ensure GitLab directory exists
      ansible.builtin.file:
        path: /etc/gitlab
        state: directory
        owner: root
        group: root
        mode: '0775'

    - name: Create file to detect a failed reconfigure
      ansible.builtin.copy:
        content: "This file is managed by Ansible."
        dest: /etc/gitlab/reconfigure_failed
        force: false
        owner: root
        group: root
        mode: '0644'

    - name: Stop role execution due to failed package installation
      ansible.builtin.fail:

...
