- name: Check if local copy of Signalilo exists
  ansible.builtin.stat:
    path: "{{ playbook_dir }}/signalilo_bin"
  register: signalilo_check
  delegate_to: localhost

- name: Get signalilo binary from image using Podman
  ansible.builtin.shell:
    cmd: export IMG="quay.io/vshn/signalilo:latest" && podman pull $IMG && export ID=$(podman create $IMG) && podman cp $ID:/usr/local/bin/signalilo {{ playbook_dir }}/signalilo_bin && podman rm $ID
  delegate_to: localhost
  when: signalilo_check.stat.exists == false

- name: Check again if local copy of Signalilo exists
  ansible.builtin.stat:
    path: "{{ playbook_dir }}/signalilo_bin"
  register: signalilo_check2
  delegate_to: localhost

- name: Ensure group signalilo exists
  ansible.builtin.group:
    name: signalilo
    state: present
  become: true

- name: Add the user signalilo
  ansible.builtin.user:
    name: signalilo
    comment: Signalilo service user
    shell: /usr/sbin/nologin
    group: signalilo
  become: true

- name: Copy Signalilo
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/signalilo_bin"
    dest: /usr/local/bin/signalilo
    owner: root
    group: root
    mode: '0755'
  become: true
  when: signalilo_check2.stat.exists == True

- name: Create env file for configuration
  ansible.builtin.template:
    src: signalilo.env.j2
    dest: /usr/local/etc/signalilo.env
    owner: signalilo
    group: signalilo
    mode: '0640'
  become: true

- name: Copy systemd service
  ansible.builtin.copy:
    src: signalilo.service
    dest: /etc/systemd/system/signalilo.service
    owner: root
    group: root
    mode: '0644'
  become: true

- name: Start Signalilo
  ansible.builtin.systemd:
    state: started
    enabled: true
    name: signalilo
    daemon_reload: true
  become: true
